apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: axon
  annotations:
    kubernetes.io/ingress.class: "nginx"
    external-dns.alpha.kubernetes.io/hostname: digipnyx.org
  name: axon-ingress
spec:
  rules:
  - host: axon1-testnet
    http:
      paths:
      - path: /
        pathType: Prefix      
        backend:
          service:
            name: axon1
            port:
                number: 8100
  - host: axon2-testnet
    http:
      paths:
      - path: /
        pathType: Prefix      
        backend:
          service:
            name: axon2
            port:
                number: 8100
        # backend:
        #   serviceName: axon2
        #   servicePort: 8100

  - host: axon3-testnet
    http:
      paths:
      - path: /
        pathType: Prefix      
        backend:
          service:
            name: axon3
            port:
                number: 8100
        # backend:
        #   serviceName: axon3
        #   servicePort: 8100

  - host: axon4-testnet
    http:
      paths:
      - path: /
        pathType: Prefix      
        backend:
          service:
            name: axon4
            port:
                number: 8100
        # backend:
        #   serviceName: axon4
        #   servicePort: 8100
