apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  basicAuth: false

  
- name: Prometheus-loki
  type: prometheus
  access: proxy
  url: http://axon-loki:3100/loki
  basicAuth: false

- name: jaeger
  type: jaeger
  access: proxy
  url: http://jaeger-query:16686
  basicAuth: false

- name: Elasticsearch-axon
  type: elasticsearch
  access: proxy
  database: 'axon-*'
  url: http://localhost:9200
  jsonData:
    interval: nil
    timeField: '@timestamp'
    esVersion: 70
