{
 "title": "Axon nodes",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Blocks produced in the last 1 minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(axon_consensus_height[1m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Consensus height",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "axon_consensus_height", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Number of committed transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axon_consensus_committed_tx_total",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Number of transactions in mempool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "axon_mempool_co_queue_count", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Connected consensus peers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axon_network_connected_consensus_peers",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Connected peers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "axon_network_connected_peers", "legendFormat": "{{service}}" }
   ]
  }
 ]
}