---
- name: uni contract
  hosts: localhost
  become: yes
  become_method: sudo
  vars_files:
    - config.yml
  tasks:
  ###############################################################################################################
    - name: Copy the axon file
      copy:
        src: ./templates/deploy.js
        dest: ./deploy.js
        mode: 0755
    - name: Replace url
      shell: sed -i "s/node_address/{{ node_address }}/g" "./deploy.js"
      become: yes
      become_method: sudo
    - name: npm install
      shell: yarn add web3 ethers && node deploy.js
      become: yes
      become_method: sudo
