---
- name: uni deploy
  hosts: localhost
  become: yes
  become_method: sudo
  vars_files:
    - config.yml
    - ../uni-v2-contract-deploy/contract_Uni_V2_Address.yaml
  tasks:
    ###############################################################################################################
    - name: rm uni-interface
      shell: "rm -rf {{ deploy_path }}"
      become: yes
      become_method: sudo
      tags:
        - up

    - name: mkdir {{ deploy_path }}
      shell: "mkdir -p {{ deploy_path }}"
      become: yes
      become_method: sudo
      tags:
        - up

    - name: Pull code
      git:
        repo: "https://github.com/Uniswap/uniswap-interface.git"
        dest: "{{ deploy_path }}"
        version: "v2.6.5"
        force: yes
      become: yes
      become_method: sudo
      tags:
        - up

    - name: uni-interface docker config
      copy:
        src: ./templates/docker-compose.yml
        dest: "{{ deploy_path }}/docker-compose.yml"
        mode: 0755
      tags:
        - up

    - name: Replace listen_on_port
      replace:
        path: "{{ deploy_path }}/docker-compose.yml"
        regexp: 'listen_on_port'
        replace: "{{ listen_on_port }}"
      tags:
        - up

    - name: uni-interface shutdown
      shell: "docker-compose -f {{ deploy_path }}/docker-compose.yml down"
      tags:
        - up

    - name: yarn install
      shell: "cd {{ deploy_path }} && yarn install"
      tags:
        - up

    ###############################################################################################################
    - name: Replace REACT_APP_CHAIN_ID  in .env
      shell: sed -i "s/1/5/g" "{{ deploy_path }}/.env"
      tags:
        - up

    - name: Replace ROUTER_ADDRESS to UniswapV2Router02
      shell: sed -i "s/0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D/{{ UniswapV2Router02 }}/g" "{{ deploy_path }}/src/constants/index.ts"
      tags:
        - up

    - name: Replace ROUTER_ADDRESS to UniswapV2Router02
      shell: sed -i "s/0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D/{{ UniswapV2Router02 }}/g" "{{ deploy_path }}/src/state/swap/hooks.ts"
      tags:
        - up

    - name: Replace `FACTORY_ADDRESS` in the sdk.cjs.development.js with `UniswapV2Factory`
      shell: sed -i "s/0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f/{{ UniswapV2Factory }}/g" "{{ deploy_path }}/node_modules/@uniswap/sdk/dist/sdk.cjs.development.js"
      tags:
        - up 

    - name: Replace `FACTORY_ADDRESS` in the hooks.ts
      shell: sed -i "s/0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f/{{ UniswapV2Factory }}/g" "{{ deploy_path }}/src/state/swap/hooks.ts"
      tags:
        - up 

    - name: Replace `FACTORY_ADDRESS` in the sdk.esm.js with `UniswapV2Factory`
      shell: sed -i "s/0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f/{{ UniswapV2Factory }}/g" "{{ deploy_path }}/node_modules/@uniswap/sdk/dist/sdk.esm.js"
      tags:
        - up

    - name: Replace `WEHT_ADDRESS` in the sdk.cjs.development.js with `WETH`
      shell: sed -i "s/0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6/{{ WETH }}/g" "{{ deploy_path }}/node_modules/@uniswap/sdk/dist/sdk.cjs.development.js"
      tags:
        - up

    - name: Replace `WEHT_ADDRESS` in the sdk.esm.js with `WETH`
      shell: sed -i "s/0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6/{{ WETH }}/g" "{{ deploy_path }}/node_modules/@uniswap/sdk/dist/sdk.esm.js"
      tags:
        - up

    - name: Replace `INIT_CODE_HASH` in the sdk.cjs.development.js with `${INIT_CODE_HASH}`
      shell: sed -i "s/0x96e8ac4277198ff8b6f785478aa9a39f403cb768dd02cbee326c3e7da348845f/{{ InitCodeHash }}/g" "{{ deploy_path }}/node_modules/@uniswap/sdk/dist/sdk.cjs.development.js"
      tags:
        - up
    
    - name: Replace `INIT_CODE_HASH` in the sdk.esm.js with `${INIT_CODE_HASH}`
      shell: sed -i "s/0x96e8ac4277198ff8b6f785478aa9a39f403cb768dd02cbee326c3e7da348845f/{{ InitCodeHash }}/g" "{{ deploy_path }}/node_modules/@uniswap/sdk/dist/sdk.esm.js"
      tags:
        - up

    - name: Replace MuiltiCall_ADDRESS to MuiltiCall
      shell: sed -i "s/0x77dCa2C955b15e9dE4dbBCf1246B4B85b651e50e/{{ Multicall }}/g" "{{ deploy_path }}/src/constants/multicall/index.ts"
      tags:
        - up

    ###########################################################################################################
    - name: yarn build
      shell: "cd {{ deploy_path }} && yarn build"
      # become: yes
      # become_method: sudo
      tags:
        - up

    - name: uni-interface deploy
      shell: "cd {{ deploy_path }} && docker-compose up -d"
      tags:
        - up
    ###########################################################################################################
    - name: uni-interface down
      shell: "cd {{ deploy_path }} && docker-compose down"
      tags:
        - down

    - name: clean up uni-interface
      shell: "rm -rf {{ deploy_path }}"
      become: yes
      become_method: sudo
      tags:
        - down
