---
- name: uni deploy
  hosts: localhost
  become: yes
  become_method: sudo
  vars_files:
    - config.yml
    - ../uni-v2-contract-deploy/contract_Uni_V2_Address.yaml
  tasks:
    ###############################################################################################################
    - name: rm uni-interface
      shell: "rm -rf {{ deploy_path }}"
      become: yes
      become_method: sudo
      tags:
        - up

    - name: mkdir {{ deploy_path }}
      shell: "mkdir -p {{ deploy_path }}"
      become: yes
      become_method: sudo
      tags:
        - up

    - name: Pull code
      git:
        repo: "https://github.com/Uniswap/uniswap-interface.git"
        dest: "{{ deploy_path }}"
        version: "v2.6.5"
        force: yes
      become: yes
      become_method: sudo
      tags:
        - up

    - name: docker-compose
      shell: "cp ./templates/docker-compose.yml {{ deploy_path }}"
      become: yes
      become_method: sudo
      tags:
        - up

    - name: Replace listen_on_port
      replace:
        path: "{{ deploy_path }}/docker-compose.yml"
        regexp: 'listen_on_port'
        replace: "{{ listen_on_port }}"
      tags:
        - up

    - name: uni-interface shutdown
      shell: "docker-compose -f {{ deploy_path }}/docker-compose.yml down"
      tags:
        - up

    - name: yarn install
      shell: "cd {{ deploy_path }} && yarn install"
      tags:
        - up

    ###############################################################################################################
    - name: Replace ROUTER_ADDRESS to UniswapV2Router02
      replace:
        path: "{{ deploy_path }}/src/constants/index.ts"
        regexp: '0xc4A3C40808d63e1eE18f7739F239dfA5Bc92bFCd'
        replace: "{{ UniswapV2Router02 }}"
      tags:
        - up

    - name: Replace `FACTORY_ADDRESS` in the axonuniswapsdk.cjs.development.js with `UniswapV2Factory`
      replace:
        path: "{{ deploy_path }}/node_modules/@uniswap/sdk/dist/sdk.cjs.development.js"
        regexp: '0xb484fd480E598621638F380F404697Cd9f58B0F8'
        replace: "{{ UniswapV2Factory }}"
      tags:
        - up

    - name: Replace `WEHT_ADDRESS` in the axonuniswapsdk.cjs.development.js with `WETH`
      replace:
        path: "{{ deploy_path }}/node_modules/@uniswap/sdk/dist/sdk.cjs.development.js"
        regexp: '0xb9dc8Bde1DB42410D304b5e78c2ff843134E15e0'
        replace: "{{ WETH }}"
      tags:
        - up

    - name: Replace `INIT_CODE_HASH` in the axonuniswapsdk.cjs.development.js with `${INIT_CODE_HASH}`
      replace:
        path: "{{ deploy_path }}/node_modules/@uniswap/sdk/dist/sdk.cjs.development.js"
        regexp: '0xfe5c25035eb1580fcbc8496a5d5423870718fac54c9d582b43039dbce6afc72f'
        replace: "{{ InitCodeHash }}"
      tags:
        - up

    - name: Replace MuiltiCall_ADDRESS to MuiltiCall
      replace:
        path: "{{ deploy_path }}/src/constants/multicall/index.ts"
        regexp: '0x77dCa2C955b15e9dE4dbBCf1246B4B85b651e50e'
        replace: "{{ Multicall }}"
      tags:
        - up

    ###########################################################################################################
    - name: yarn build
      shell: "cd {{ deploy_path }} && yarn build"
      # become: yes
      # become_method: sudo
      tags:
        - up

    - name: uni-interface docker config
      copy:
        src: ./templates/docker-compose.yml
        dest: "{{ deploy_path }}/docker-compose.yml"
        mode: 0755
      tags:
        - up

    - name: uni-interface deploy
      shell: "cd {{ deploy_path }} && docker-compose up -d"
      tags:
        - up
    ###########################################################################################################
    - name: uni-interface down
      shell: "cd {{ deploy_path }} && docker-compose down"
      tags:
        - down

    - name: clean up uni-interface
      shell: "rm -rf {{ deploy_path }}"
      become: yes
      become_method: sudo
      tags:
        - down
