{
 "title": "Dashboard v2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "TPS",
   "type": "graph",
   "description": "rate of committed transactions for each node in this network",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(muta_consensus_committed_tx_total[5m]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "consensus_p90",
   "type": "graph",
   "description": "lower is better",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.90, sum(rate(muta_consensus_duration_seconds_bucket[5m])) by (le, instance)))",
     "legendFormat": "time_usage(s)"
    }
   ]
  },
  {
   "title": "processed_tx_request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(muta_api_request_result_total{type=\"send_transaction\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(muta_api_request_result_total{result=\"success\",type=\"send_transaction\"}[5m]))",
     "legendFormat": "Success Total"
    },
    {
     "expr": "rate(muta_api_request_result_total{result=\"success\", type=\"send_transaction\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "current_height",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(muta_consensus_height)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "synced_block",
   "type": "graph",
   "description": "lower is better. Number of blocks generated by the synchronization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "muta_consensus_sync_block_total ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "network_message_arrival_rate",
   "type": "graph",
   "description": "Estimate the network message arrival rate in the last five minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "((sum(muta_network_message_total{type=\"gossip\", direction=\"received\"}) / 20) +\n (sum(muta_network_message_total{type!=\"gossip\", direction=\"received\"})) )\n/\nsum(muta_network_message_total{direction=\"sent\"}) \n"
    }
   ]
  },
  {
   "title": "consensus_round_cost",
   "type": "graph",
   "description": "lower is better, no data when all nodes consensus with round 0.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "(muta_consensus_round > 0 )", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "mempool_cached_tx",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "muta_mempool_tx_count", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}