{
 "title": "muta-network-dev",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Instance",
    "query": "label_values(muta_consensus_height, instance)"
   },
   {
    "name": "device",
    "label": "NIC",
    "query": "label_values(node_network_info{device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
   },
   {
    "name": "node2",
    "label": "node2",
    "query": "label_values(node_uname_info,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Network bandwidth usage per second $device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$node2\",device=~\"$device\"}[5m])*8",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$node2\",device=~\"$device\"}[5m])*8",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Internet traffic per hour $device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{instance=~\"$node2\",device=~\"$device\"}[60m])",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{instance=~\"$node2\",device=~\"$device\"}[60m])",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "mempool_cached_tx",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "muta_mempool_tx_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "height and round",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "muta_consensus_height{instance=~\"$node\"}",
     "legendFormat": "height"
    },
    {
     "expr": "(muta_consensus_round{instance=~\"$node\"} > 0 )",
     "legendFormat": "round"
    }
   ]
  },
  {
   "title": "consensus_round_cost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "(muta_consensus_round > 0 )", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "current_height",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(muta_consensus_height)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "synced_block",
   "type": "graph",
   "description": "lower is better. Number of blocks generated by the synchronization",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "muta_consensus_sync_block_total ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "processed_tx_request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(muta_api_request_result_total{type=\"send_transaction\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(muta_api_request_result_total{result=\"success\",type=\"send_transaction\"}[5m]))",
     "legendFormat": "Success Total"
    },
    {
     "expr": "rate(muta_api_request_result_total{result=\"success\", type=\"send_transaction\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "muta_network_message_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(url:muta_network_message_size:sum5m{direction=\"send\"}) by (instance)",
     "legendFormat": "send-total-{{instance}}"
    },
    {
     "expr": "sum(url:muta_network_message_size:sum5m{direction=\"received\"}) by (instance)",
     "legendFormat": "received-total-{{instance}}"
    },
    {
     "expr": "sum(url:muta_network_message_size:sum5m{direction=\"send\"})",
     "legendFormat": "send-total"
    },
    {
     "expr": "sum(url:muta_network_message_size:sum5m{direction=\"received\"})",
     "legendFormat": "received-total"
    }
   ]
  },
  {
   "title": "network_send_by_url_size_and_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "bytes", "label": "bits" }
   ],
   "targets": [
    {
     "expr": "sum(url:muta_network_message_size:sum5m{direction=\"send\",instance=~\"$node\"}) by (url)",
     "legendFormat": "{{url}}"
    },
    {
     "expr": "sum(rate(muta_network_message_total{direction=\"sent\"}[5m])) by (action)",
     "legendFormat": "count_{{action}}"
    }
   ]
  },
  {
   "title": "network_received_by_url_size_and_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(url:muta_network_message_size:sum5m{direction=\"received\",instance=~\"$node\"}) by (url)",
     "legendFormat": "{{url}}"
    },
    {
     "expr": "sum(rate(muta_network_message_total{direction=\"received\"}[5m])) by (action)",
     "legendFormat": "count_{{action}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connected Peers",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "muta_network_connected_peers", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Connected Peers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(muta_network_saved_peer_count)",
       "legendFormat": "Saved peers"
      },
      { "expr": "muta_network_connected_peers\r", "legendFormat": "Connected Peers" }
     ]
    },
    {
     "title": "Connected Consensus Peers (Minus itself)",
     "type": "gauge",
     "description": "The right number should be total number of consensus peers minus 1 (Itself). For example, 9 consensus peers, then the right number should be 8.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "muta_network_connected_consensus_peers",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Connected Consensus Peers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(muta_network_tagged_consensus_peers\r)",
       "legendFormat": "Consensus peers"
      },
      {
       "expr": "muta_network_connected_consensus_peers\r",
       "legendFormat": "{{instance}}-Connected Consensus Peers (Minus itself)"
      }
     ]
    },
    {
     "title": "Saved peers",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "muta_network_saved_peer_count", "legendFormat": "Saved peers" }
     ]
    },
    {
     "title": "Unidentified Connections",
     "type": "gauge",
     "description": "Processing identify protocol handshake, etc verify chain id.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "muta_network_unidentified_connections",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Connecting Peers",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "muta_network_outbound_connecting_peers",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disconnected count(To other peers)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "muta_network_ip_disconnected_count",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Received messages in processing",
     "type": "gauge",
     "description": "Total number of received messages in processing",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "muta_network_received_message_in_processing_guage",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Received messages in processing by ip",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "muta_network_received_ip_message_in_processing_guage{instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "Ping (ms)_p90",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.90, sum(rate(muta_network_ping_in_ms_bucket[5m])) by (le, instance)))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Peer give up warnings",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
     "targets": [
      {
       "expr": "{level=\"WARN\"} |~ \"give up\""
      }
     ]
    }
   ]
  }
 ]
}