{
 "title": "muta-benchmark",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Instance",
    "query": "label_values(muta_consensus_height, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "TPS",
   "type": "graph",
   "description": "rate of committed transactions for each node in this network",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(muta_consensus_committed_tx_total[5m]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "exec_p90",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.90, sum(rate(muta_consensus_time_cost_seconds_bucket{type=\"exec\"}[5m])) by (le, instance)))"
    }
   ]
  },
  {
   "title": "consensus_round_cost",
   "type": "graph",
   "description": "lower is better, no data when all nodes consensus with round 0.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "(muta_consensus_round > 0 )", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "consensus_p90",
   "type": "graph",
   "description": "lower is better",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.90, sum(rate(muta_consensus_duration_seconds_bucket[5m])) by (le, instance)))",
     "legendFormat": "time_usage(s)"
    }
   ]
  },
  {
   "title": "get_cf_each_block_time_usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (sum by (instance) (increase(muta_storage_get_cf_seconds[5m]))) / avg(increase(muta_consensus_height[5m]))"
    }
   ]
  },
  {
   "title": "put_cf_each_block_time_usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (sum by (instance) (increase(muta_storage_put_cf_seconds[5m]))) / avg(increase(muta_consensus_height[5m]))"
    }
   ]
  },
  {
   "title": "processed_tx_request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(muta_api_request_result_total{type=\"send_transaction\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(muta_api_request_result_total{result=\"success\",type=\"send_transaction\"}[5m]))",
     "legendFormat": "Success Total"
    },
    {
     "expr": "rate(muta_api_request_result_total{result=\"success\", type=\"send_transaction\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "current_height",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(muta_consensus_height)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Liveness",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(muta_consensus_height{job=\"muta_exporter\"}[1m])",
     "legendFormat": "Liveness"
    }
   ]
  },
  {
   "title": "synced_block",
   "type": "graph",
   "description": "lower is better. Number of blocks generated by the synchronization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "muta_consensus_sync_block_total ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "network_message_arrival_rate",
   "type": "graph",
   "description": "Estimate the network message arrival rate in the last five minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(\r\n  # broadcast_count * (instance_count - 1)\r\n  sum(increase(muta_network_message_total{target=\"all\", direction=\"sent\"}[5m])) * (count(count by (instance) (muta_network_message_total)) - 1)\r\n  # unicast_count\r\n  + sum(increase(muta_network_message_total{target=\"single\", direction=\"sent\"}[5m]))\r\n) \r\n/\r\n# received_count\r\n(sum(increase(muta_network_message_total{direction=\"received\"}[5m])))\n"
    }
   ]
  },
  {
   "title": "mempool_cached_tx",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "muta_mempool_tx_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Saved peers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "muta_network_saved_peer_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Consensus peers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "muta_network_tagged_consensus_peers",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "muta_network_connected_peers", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Connected Consensus Peers (Minus itself)",
   "type": "gauge",
   "description": "The right number should be total number of consensus peers minus 1 (Itself). For example, 9 consensus peers, then the right number should be 8.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "muta_network_connected_consensus_peers",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connecting Peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "muta_network_outbound_connecting_peers",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Unidentified Connections",
   "type": "gauge",
   "description": "Processing identify protocol handshake, etc verify chain id.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "muta_network_unidentified_connections",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received messages in processing",
   "type": "gauge",
   "description": "Total number of received messages in processing",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "muta_network_received_message_in_processing_guage",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received messages in processing by ip",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "muta_network_received_ip_message_in_processing_guage"
    }
   ]
  },
  {
   "title": "Ping (ms)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    { "expr": "muta_network_ip_ping_in_ms", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Ping by ip",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "muta_network_ip_ping_in_ms" }
   ]
  },
  {
   "title": "Disconnected count(To other peers)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "muta_network_ip_disconnected_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Peer give up warnings",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "targets": [
    {
     "expr": "{filename=\"/opt/muta.log\"} |~ \"WARN\" |~ \"give up\""
    }
   ]
  }
 ]
}