---
################################################ deploy v3 contract ###############################################################
- name: uni deploy v3 contract
  hosts: v3
  become: yes
  become_method: sudo
  vars_files:
    - config.yml
  tasks:
    - name: delete the {{ v3_contract_deploy_path }}
      shell: "rm -rf {{ v3_contract_deploy_path }}"
      ignore_errors: yes
      tags:
        - v3-contract

    - name: Pull code
      git:
        repo: "https://github.com/Uniswap/deploy-v3.git"
        dest: "{{ v3_contract_deploy_path }}"
        version: "v1.0.0"
        force: yes
      become: yes
      become_method: sudo
      tags:
        - v3-contract

    - name: yarn install
      shell: "cd {{ v3_contract_deploy_path }} && yarn install"
      tags:
        - v3-contract    

    - name: deploy uniswap v3 contracts
      shell: "cd {{ v3_contract_deploy_path }} && yarn start -pk {{ hex_private_key }} -j {{ node_address }} -w9 {{ WETH }} -o  {{ hex_pub_address }} -ncl AT"
      tags:
        - v3-contract
    - name: cat state.json
      shell: "cd {{ v3_contract_deploy_path }} && cat state.json"
      tags:
        - v3-contract
