{
 "title": "axon-benchmark",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(muta_consensus_height, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "TPS",
   "type": "graph",
   "description": "rate of committed transactions for each node in this network",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(axon_consensus_committed_tx_total[5m]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "exec_p90",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.90, sum(rate(axon_consensus_time_cost_seconds_bucket{type=\"exec\"}[5m])) by (le, instance)))",
     "legendFormat": "exec_90"
    }
   ]
  },
  {
   "title": "consensus_round_cost",
   "type": "graph",
   "description": "lower is better, no data when all nodes consensus with round 0.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "(axon_consensus_round > 0 )", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "consensus_p90",
   "type": "graph",
   "description": "lower is better",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.90, sum(rate(axon_consensus_duration_seconds_bucket[5m])) by (le, instance)))",
     "legendFormat": "time_usage(s)"
    }
   ]
  },
  {
   "title": "get_cf_each_block_time_usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (sum by (instance) (increase(axon_storage_get_cf_seconds[5m]))) / avg(increase(axon_consensus_height[5m]))"
    }
   ]
  },
  {
   "title": "put_cf_each_block_time_usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (sum by (instance) (increase(axon_storage_put_cf_seconds[5m]))) / avg(increase(axon_consensus_height[5m]))"
    }
   ]
  },
  {
   "title": "current_height",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(axon_consensus_height)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "check_block_cost_p90",
   "type": "graph",
   "description": "lower is better",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.90, sum(rate(axon_consensus_check_block_bucket{type=\"check_block_cost\"}[5m])) by (le, instance)))",
     "legendFormat": "check_block_cost"
    },
    {
     "expr": "avg(histogram_quantile(0.90, sum(rate(axon_consensus_check_block_bucket{type=\"write_wal_cost\"}[5m])) by (le, instance)))",
     "legendFormat": "write_wal_cost"
    }
   ]
  },
  {
   "title": "synced_block",
   "type": "graph",
   "description": "lower is better. Number of blocks generated by the synchronization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "axon_consensus_sync_block_total ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Liveness",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(axon_consensus_height{job=\"axon_exporter\"}[1m])",
     "legendFormat": "Liveness"
    }
   ]
  },
  {
   "title": "mempool_cached_tx",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "axon_mempool_tx_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "processed_tx_request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(axon_api_request_result_total{type=\"send_transaction\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(axon_api_request_result_total{result=\"success\",type=\"send_transaction\"}[5m]))",
     "legendFormat": "Success Total"
    },
    {
     "expr": "rate(axon_api_request_result_total{result=\"success\", type=\"send_transaction\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "processed_rpc_request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(axon_api_request_result_total[5m])) by (type)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(axon_api_request_result_total{result=\"success\"}[5m])) by (type)",
     "legendFormat": "Success Total"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "network_message_arrival_rate",
   "type": "graph",
   "description": "Estimate the network message arrival rate in the last five minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(\n  # broadcast_count * (instance_count - 1)\n  sum(increase(axon_network_message_total{target=\"all\", direction=\"sent\"}[5m])) * (count(count by (instance) (axon_network_message_total)) - 1)\n  # unicast_count\n  + sum(increase(axon_network_message_total{target=\"single\", direction=\"sent\"}[5m]))\n) \n/\n# received_count\n(sum(increase(axon_network_message_total{direction=\"received\"}[5m])))\n"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(axon_network_saved_peer_count)",
     "legendFormat": "Saved peers"
    },
    { "expr": "axon_network_connected_peers", "legendFormat": "Connected Peers" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "axon_network_connected_peers", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Connected Consensus Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(axon_network_tagged_consensus_peers)",
     "legendFormat": "Consensus peers"
    },
    {
     "expr": "axon_network_connected_consensus_peers",
     "legendFormat": "{{instance}}-Connected Consensus Peers (Minus itself)"
    }
   ]
  },
  {
   "title": "Connected Consensus Peers (Minus itself)",
   "type": "gauge",
   "description": "The right number should be total number of consensus peers minus 1 (Itself). For example, 9 consensus peers, then the right number should be 8.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "axon_network_connected_consensus_peers",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Unidentified Connections",
   "type": "gauge",
   "description": "Processing identify protocol handshake, etc verify chain id.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axon_network_unidentified_connections",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Saved peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "axon_network_saved_peer_count", "legendFormat": "Saved peers" }
   ]
  },
  {
   "title": "Disconnected count(To other peers)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axon_network_ip_disconnected_count",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connecting Peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "axon_network_outbound_connecting_peers",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received messages in processing by ip",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "axon_network_received_ip_message_in_processing_guage{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Received messages in processing",
   "type": "gauge",
   "description": "Total number of received messages in processing",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "axon_network_received_message_in_processing_guage",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ping (ms)_p90",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.90, sum(rate(axon_network_ping_in_ms_bucket[5m])) by (le, instance)))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}