apiVersion: v1
kind: Service
metadata:
  labels:
    app: axon1
  name: axon1
  namespace: axon
spec:
  ports:
    - name: p2p
      port: 8001
      targetPort: 8001
      protocol: TCP
    - name: rpc
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: websocket
      port: 8010
      targetPort: 8010
      protocol: TCP
    - name: prometheus
      port: 8100
      targetPort: 8100
      protocol: TCP
  selector:
    app: axon1
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: axon1
  namespace: axon
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: axon-test
      app: axon1
      logging: "true"
  serviceName: "axon1"
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        svc: axon-test
        app: axon1
        logging: "true"
    spec:
      containers:
        - name: axon1
          args:
            - ./axon
            - -c=/app/devtools/chain/k8s/node_1.toml
            - -g=/app/devtools/chain/genesis.json
          image: zhengjianhui/axon-k8s:latest
          volumeMounts:
          - name: config-node1
            mountPath: /app/devtools/chain/k8s/node_1.toml
            subPath: node_1.toml
          - name: config-genesis
            mountPath: /app/devtools/chain/genesis.json
            subPath: genesis.json
          - name: config-db-options
            mountPath: /app/devtools/chain/k8s/default.db-options
            subPath: default.db-options
          - name: data1
            mountPath: /app/devtools/chain/data1
            subPath: data1
          ports:
          - name: p2p
            containerPort: 8001
          - name: rpc
            containerPort: 8000
          - name: websocket
            containerPort: 8010
          - name: prometheus
            containerPort: 8100
        - name: jaeger-agent-new
          image: jaegertracing/jaeger-agent:1.32
          env:
          - name: JACGER_COLLECTOR_ADDRESS
            value: jaeger-collector:14250
          - name: JACGER_AGENT_PORT
            value: "6831"
          args: ['--reporter.grpc.host-port=$(JACGER_COLLECTOR_ADDRESS)']
          resources: {}
          securityContext:
            privileged: true
      volumes:
        - name: config-node1
          configMap:
            name: node1-toml
        - name: config-genesis
          configMap:
            name: genesis
        - name: config-db-options
          configMap:
            name: db-options
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: data1
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: gp2
      resources:
        requests:
          storage: 100Gi
