server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/promtail/positions.yaml   
  sync_period: 10s 

clients:
  - url: http://LOKI_ADDRESS:8103/api/prom/push

scrape_configs:
  - job_name: axon-logs
    pipeline_stages: 
    - json:
        expressions:
          level: level
          message: message
          time: time
          module_path: module_path
          file: file
          line: line   
    - labels:
        level:
        message:
        time:
        module_path:
        file:
        line:
    static_configs:
      - targets:
          - localhost
        labels:
          job: axon-logs
          app: axon
          hostip: host.docker.internal
          __path__: /var/logs/*log
