deploy_path: "/home/ckb/axon-benchmark"
axon_repo: "https://github.com/nervosnetwork/axon.git"
axon_branch: "main"
enable_cross_client: "false"
mercury_uri: "http://127.0.0.1:8116"
network: 'multi_address = "/ip4/0.0.0.0/tcp/8001/p2p/QmNk6bBwkLPuqnsrtxpp819XLZY3ymgjs3p1nKtxBVgqxj"'
