version: '3'

services:
  axon:
    container_name: axon-benchmark
    image:  zhengjianhui/axon-benchmark:latest
    restart: always
    privileged: true
    volumes:
      - ./config.json:/benchmark/config.json
      - ./logs:/benchmark/logs
    command: node index.js --benchmark_cases="['./benchmark']"
