apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: axon-logs-claim
spec:
  storageClassName: axon-logs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi