apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  labels:
    type: local
  name: axon-devtools-pv
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: "/home/ckb/k8s-deploy/k8s-deploy/devtools"
    
