apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: axon-logs-pvc
spec:
  storageClassName: "axon-logs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi