apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: axon-devtools-claim
spec:
  storageClassName: axon-devtools
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi