apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  labels:
    type: local
  name: axon-logs-pv
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 200Mi
  hostPath:
    path: "/home/ckb/k8s-deploy/k8s-deploy/logs"
    
