apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: axon-devtools-pvc
spec:
  storageClassName: "axon-devtools"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi