SHELL = bash
axon-deploy:
	# /home/ckb/axon-devops/k8s-deploy/k8s/axon/deploy.sh deploy
		/home/ckb/axon-devops/k8s-deploy/deploy.sh deploy

axon-clean:
	/home/ckb/axon-devops/k8s-deploy/k8s/axon/deploy.sh clean

benchmark-deploy:
	/home/ckb/axon-devops/k8s-deploy/k8s/benchmark/deploy.sh deploy

benchmark-clean:
	/home/ckb/axon-devops/k8s-deploy/k8s/benchmark/deploy.sh clean

fluntd-deploy:
	/home/ckb/axon-devops/k8s-deploy/k8s/eks/fluent/deploy.sh deploy

fluntd-clean:
	/home/ckb/axon-devops/k8s-deploy/k8s/eks/fluent/deploy.sh clean

